export const PLAYER_INIT = 'PLAYER_INIT';
export const PLAYER_READY = 'PLAYER_READY';
export const UPDATE_PLAYBACK_STATE = 'UPDATE_PLAYBACK_STATE';
export const UPDATE_CURRENT_TIME = 'UPDATE_CURRENT_TIME';
export const UPDATE_DURATION = 'UPDATE_DURATION';
export const UPDATE_MUTE_STATE = 'UPDATE_MUTE_STATE';
