export const STATES = {
    INITIALIZING: 'INITIALIZING',
    INITIALIZED: 'INITIALIZED',
    FAILURE: 'FAILURE',
    READY: 'READY',
    UNSTARTED: 'UNSTARTED',
    ENDED: 'ENDED',
    PLAYING: 'PLAYING',
    PAUSED: 'PAUSED',
    BUFFERING: 'BUFFERING',
    CUED: 'CUED',
    DESTROYED: 'DESTROYED',
};

export const VENDORS = {
    'YOUTUBE': 'YOUTUBE',
    'VIMEO': 'VIMEO',
    // 'MP4': 'MP4',
    'HTML5': 'HTML5',
    'WISTIA': 'WISTIA',
};

export const ACTIONS = {
    PLAY: 'PLAY',
    PAUSE: 'PAUSE',
    STOP: 'STOP',
    MUTE: 'MUTE',
    UNMUTE: 'UNMUTE',
    SEEK_TO: 'SEEK_TO',
    CHANGE_SOURCE: 'CHANGE_SOURCE',
};

export const ON_PLAYER_STATE_CHANGE = 'ON_PLAYER_STATE_CHANGE';

export const ON_TIME_UPDATE = 'ON_TIME_UPDATE';
